export const TIPO_EXPORTACION_RESUMEN = 'Resumen'
export const TIPO_EXPORTACION_DETALLE = 'Detalle'
export const TIPO_EXPORTACION_CHATS = 'Chats'

export const tiposExportacion = [
  TIPO_EXPORTACION_RESUMEN,
  TIPO_EXPORTACION_DETALLE,
  TIPO_EXPORTACION_CHATS
]